{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.138",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "3yo7kychqnbirgcquezl4fww7y"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.138.jar",
          "url": "plugin-3.0.138.jar",
          "size": 122986,
          "sha512": "7854a3d4b63e01cc46f8932ee7c55907e477edeb9735f351d2f0749a84c97b5f321b0f1892df282a1a786d8178bd67e1870542ecbb24a545291b26b7357970c8",
          "sha256": "a1fba78f103ab6ac071d6211712be919809726e89e1f1e0866a61826033e0159",
          "sha1": "90ac8e893e911706c23e669feb821af571a59dcf",
          "md5": "c32437b8390628ad20301c317f0de5d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.138.jar",
          "url": "plugin-3.0.138.jar",
          "size": 122986,
          "sha512": "7854a3d4b63e01cc46f8932ee7c55907e477edeb9735f351d2f0749a84c97b5f321b0f1892df282a1a786d8178bd67e1870542ecbb24a545291b26b7357970c8",
          "sha256": "a1fba78f103ab6ac071d6211712be919809726e89e1f1e0866a61826033e0159",
          "sha1": "90ac8e893e911706c23e669feb821af571a59dcf",
          "md5": "c32437b8390628ad20301c317f0de5d0"
        }
      ]
    }
  ]
}
