{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.231",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.231.aar",
          "url": "Applanga-4.0.231.aar",
          "size": 409532,
          "sha512": "99af89770ad41a0c39424251369abe13a9ac152f4cd72e15d59fe84e94f96cb5dab55535c6d7a118bfc712297b9d1a21e999c26a7134cc9988b61a3167e2bcdf",
          "sha256": "1dc38cb42eb8c5545fdb9c5da96985673cfe8857322e975739818354f57bbf41",
          "sha1": "756f78c3ab911ebfc337a0426f67b1bdbf93d870",
          "md5": "50b77debfef055cd873f01bf216862dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.231.aar",
          "url": "Applanga-4.0.231.aar",
          "size": 409532,
          "sha512": "99af89770ad41a0c39424251369abe13a9ac152f4cd72e15d59fe84e94f96cb5dab55535c6d7a118bfc712297b9d1a21e999c26a7134cc9988b61a3167e2bcdf",
          "sha256": "1dc38cb42eb8c5545fdb9c5da96985673cfe8857322e975739818354f57bbf41",
          "sha1": "756f78c3ab911ebfc337a0426f67b1bdbf93d870",
          "md5": "50b77debfef055cd873f01bf216862dc"
        }
      ]
    }
  ]
}
