{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.228",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.228.jar",
          "url": "plugin-4.0.228.jar",
          "size": 144826,
          "sha512": "e089335dc86434a073262ae7e6e0437370ab686b49463da84df5090d3c92e995a3645264b73df0c8946c6303d3c570205951e3b36906cc246437edbae8b0898f",
          "sha256": "f9c914163dd3869365fc34d43a79d6c0bec42854e9b7cb645ec5341d9f546ce5",
          "sha1": "3066b23dc7f7f50b02b76aed7a747587483eb9b9",
          "md5": "28631bc8d9c77d7e5bae613648c17cc0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.228.jar",
          "url": "plugin-4.0.228.jar",
          "size": 144826,
          "sha512": "e089335dc86434a073262ae7e6e0437370ab686b49463da84df5090d3c92e995a3645264b73df0c8946c6303d3c570205951e3b36906cc246437edbae8b0898f",
          "sha256": "f9c914163dd3869365fc34d43a79d6c0bec42854e9b7cb645ec5341d9f546ce5",
          "sha1": "3066b23dc7f7f50b02b76aed7a747587483eb9b9",
          "md5": "28631bc8d9c77d7e5bae613648c17cc0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
