{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.200",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.200.jar",
          "url": "plugin-4.0.200.jar",
          "size": 124190,
          "sha512": "9b29efabc0a1ccde6ec25b5e5558779d109f07f2b322626ad77ab21d36818c851d375923d1dcdc8a7c810326696da35c4ff29c224a541f4e4c849d6bff0acffa",
          "sha256": "c224326be2961d63c372a363ff8a1dda842bc0c89a0b448b8a2543edef245c92",
          "sha1": "5dcbe1f30a52770189541c45850569fc527c7f54",
          "md5": "14da7c67f7a0a6fed5f3a5eacc950e79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.200.jar",
          "url": "plugin-4.0.200.jar",
          "size": 124190,
          "sha512": "9b29efabc0a1ccde6ec25b5e5558779d109f07f2b322626ad77ab21d36818c851d375923d1dcdc8a7c810326696da35c4ff29c224a541f4e4c849d6bff0acffa",
          "sha256": "c224326be2961d63c372a363ff8a1dda842bc0c89a0b448b8a2543edef245c92",
          "sha1": "5dcbe1f30a52770189541c45850569fc527c7f54",
          "md5": "14da7c67f7a0a6fed5f3a5eacc950e79"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
