{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.154",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "s4t6pqjymfc37fr2lybxdteui4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.154.jar",
          "url": "plugin-3.0.154.jar",
          "size": 151664,
          "sha512": "43d16d7d4f90dfb410f60453e50a224210bbc6a6d939df4b9fa6bc3435bcc9f0e88d7095329230225dc062c5d5dc852238c18b58b0978886cf898fa9182665b6",
          "sha256": "3e955708594fdd34d745086cdafa239cda87efd92f132d6d0e2df1554a32d4cb",
          "sha1": "f41c1032a52509a94b79a9b3e87807165c31035b",
          "md5": "fe17b2b8021d76aca685ff709833897f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.154.jar",
          "url": "plugin-3.0.154.jar",
          "size": 151664,
          "sha512": "43d16d7d4f90dfb410f60453e50a224210bbc6a6d939df4b9fa6bc3435bcc9f0e88d7095329230225dc062c5d5dc852238c18b58b0978886cf898fa9182665b6",
          "sha256": "3e955708594fdd34d745086cdafa239cda87efd92f132d6d0e2df1554a32d4cb",
          "sha1": "f41c1032a52509a94b79a9b3e87807165c31035b",
          "md5": "fe17b2b8021d76aca685ff709833897f"
        }
      ]
    }
  ]
}
