{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.197",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.197.jar",
          "url": "plugin-4.0.197.jar",
          "size": 121162,
          "sha512": "c0b6f33f86f73454266d3cd194376610d7118f08b4a81170393ff914c86edfc2359789af5a31aa50f5a3b351f2f5b2b12fb9a2aab1a3036822a88f6f53168aa9",
          "sha256": "887889210921c2c7231b50a5b9fa0ce091af911d0e8b993c02204010fc002e87",
          "sha1": "c9b40a58716c512eafa71f852d5f3446f5005df6",
          "md5": "68d1ac71c53afffc4bd0a5db963797a5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.197.jar",
          "url": "plugin-4.0.197.jar",
          "size": 121162,
          "sha512": "c0b6f33f86f73454266d3cd194376610d7118f08b4a81170393ff914c86edfc2359789af5a31aa50f5a3b351f2f5b2b12fb9a2aab1a3036822a88f6f53168aa9",
          "sha256": "887889210921c2c7231b50a5b9fa0ce091af911d0e8b993c02204010fc002e87",
          "sha1": "c9b40a58716c512eafa71f852d5f3446f5005df6",
          "md5": "68d1ac71c53afffc4bd0a5db963797a5"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
