{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.198",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.198.jar",
          "url": "plugin-4.0.198.jar",
          "size": 121164,
          "sha512": "6c4d6d354463eee472a0d84a459d41a2dac674eb67cd5c90350577ad6083635b6679716b1c15de01708b3361c95a9ae5a218b47996eced68209527ee51925d6b",
          "sha256": "426854d7615dd37681c194c1546389437175dd5bb13d97e06dbd8c19f8f50a5e",
          "sha1": "8c06a84b9e994f2330be6fb485cbaf717cd9e98f",
          "md5": "c1eb82ea48be3ce84b8b7b6665d8ec17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.198.jar",
          "url": "plugin-4.0.198.jar",
          "size": 121164,
          "sha512": "6c4d6d354463eee472a0d84a459d41a2dac674eb67cd5c90350577ad6083635b6679716b1c15de01708b3361c95a9ae5a218b47996eced68209527ee51925d6b",
          "sha256": "426854d7615dd37681c194c1546389437175dd5bb13d97e06dbd8c19f8f50a5e",
          "sha1": "8c06a84b9e994f2330be6fb485cbaf717cd9e98f",
          "md5": "c1eb82ea48be3ce84b8b7b6665d8ec17"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
