{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.187",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.187.jar",
          "url": "plugin-4.0.187.jar",
          "size": 121421,
          "sha512": "61b9f3a26918002f98263f6d43301b685901f523bff61eb63524cd83f589aaac438d5d5a5d09798dc9f245afe5ad6023b64154ce4149be6c8e0fef23ec6abcf0",
          "sha256": "e2c11cefd95a50c62207b9233bdb933df94ce5378c74ac9817e6b16aa72e50ab",
          "sha1": "a488ef18bb2c03440cac2665238eeda21ed2db6e",
          "md5": "3b0d8439bc179c47accc3e8d2273ec8b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.187.jar",
          "url": "plugin-4.0.187.jar",
          "size": 121421,
          "sha512": "61b9f3a26918002f98263f6d43301b685901f523bff61eb63524cd83f589aaac438d5d5a5d09798dc9f245afe5ad6023b64154ce4149be6c8e0fef23ec6abcf0",
          "sha256": "e2c11cefd95a50c62207b9233bdb933df94ce5378c74ac9817e6b16aa72e50ab",
          "sha1": "a488ef18bb2c03440cac2665238eeda21ed2db6e",
          "md5": "3b0d8439bc179c47accc3e8d2273ec8b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
