{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.163",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "74kgtzf42vesta5icjgerh5k7i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.163.jar",
          "url": "plugin-3.0.163.jar",
          "size": 160143,
          "sha512": "8e99ca4877fc0fb72af27cf5e2d7705879d594ca7c850318c233ddb33927d8d9af6d3a82e0df439c0a99fc85f025b56c13c6d364d62bf534df3f8f148c0033af",
          "sha256": "6dfb959f90ee8c5c9f72ef11f02b400f44da0408e84973d9afeaa5a0d03e1639",
          "sha1": "bdaa0450b83e4edbb9d4fc719be547d71515fe08",
          "md5": "752048b93db5f2b68da22276d308c665"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.163.jar",
          "url": "plugin-3.0.163.jar",
          "size": 160143,
          "sha512": "8e99ca4877fc0fb72af27cf5e2d7705879d594ca7c850318c233ddb33927d8d9af6d3a82e0df439c0a99fc85f025b56c13c6d364d62bf534df3f8f148c0033af",
          "sha256": "6dfb959f90ee8c5c9f72ef11f02b400f44da0408e84973d9afeaa5a0d03e1639",
          "sha1": "bdaa0450b83e4edbb9d4fc719be547d71515fe08",
          "md5": "752048b93db5f2b68da22276d308c665"
        }
      ]
    }
  ]
}
