{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.222",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.222.jar",
          "url": "plugin-4.0.222.jar",
          "size": 141590,
          "sha512": "5197b89dc4c92d88093e1931e4379fec2ea075567666e2cfd217f7f7d7944213bcc0a0cee2ea39f1df804182efe09f3f559eb7a0c0c08965b8250b73c33aaf10",
          "sha256": "d39513666b01dede86d914e4484a53b6716404a8d2fc96fc79e5a7b15585178f",
          "sha1": "7322b6a31ab0824d99ee7e2ccca6427153098698",
          "md5": "9347e59ae0022d292cac1893817575a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.222.jar",
          "url": "plugin-4.0.222.jar",
          "size": 141590,
          "sha512": "5197b89dc4c92d88093e1931e4379fec2ea075567666e2cfd217f7f7d7944213bcc0a0cee2ea39f1df804182efe09f3f559eb7a0c0c08965b8250b73c33aaf10",
          "sha256": "d39513666b01dede86d914e4484a53b6716404a8d2fc96fc79e5a7b15585178f",
          "sha1": "7322b6a31ab0824d99ee7e2ccca6427153098698",
          "md5": "9347e59ae0022d292cac1893817575a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
