{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.186",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.186.jar",
          "url": "plugin-4.0.186.jar",
          "size": 117565,
          "sha512": "86cfdf2e08363a4a4cc8faadb2bcf384cc9a566abb820710e45809d18427d8869989f63523dd234368f55b5c92f027a5e8344d2f3474e2d43356afbe31bf0687",
          "sha256": "342a2f1687fad6a05f35017b5e3443c5f04780286b3111b61bedaad2e5059a1d",
          "sha1": "47abd43727bd0b235b14fb2f46d1f978ca6b1b2e",
          "md5": "778f0a0881e02b189ff70f7dd69c92ad"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.186.jar",
          "url": "plugin-4.0.186.jar",
          "size": 117565,
          "sha512": "86cfdf2e08363a4a4cc8faadb2bcf384cc9a566abb820710e45809d18427d8869989f63523dd234368f55b5c92f027a5e8344d2f3474e2d43356afbe31bf0687",
          "sha256": "342a2f1687fad6a05f35017b5e3443c5f04780286b3111b61bedaad2e5059a1d",
          "sha1": "47abd43727bd0b235b14fb2f46d1f978ca6b1b2e",
          "md5": "778f0a0881e02b189ff70f7dd69c92ad"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
