{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.235",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.235.jar",
          "url": "plugin-4.0.235.jar",
          "size": 144826,
          "sha512": "a948339b787ce289b32f976d22b4273aa7973bfbcc8b3bb9061236a6cc474779a5b4d60b184a103fc6fca44067b81e65438046f28aef9c6ba163a086c4e23006",
          "sha256": "ed8bb225cac06f1c4523186b52b0bf1a230597eb3d59c68cdbbd1a2269e9829e",
          "sha1": "a406e14373d321e71226aece361def6dd45d82b2",
          "md5": "af8a49d1c560f6cfdb5d94bc93978316"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.235.jar",
          "url": "plugin-4.0.235.jar",
          "size": 144826,
          "sha512": "a948339b787ce289b32f976d22b4273aa7973bfbcc8b3bb9061236a6cc474779a5b4d60b184a103fc6fca44067b81e65438046f28aef9c6ba163a086c4e23006",
          "sha256": "ed8bb225cac06f1c4523186b52b0bf1a230597eb3d59c68cdbbd1a2269e9829e",
          "sha1": "a406e14373d321e71226aece361def6dd45d82b2",
          "md5": "af8a49d1c560f6cfdb5d94bc93978316"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
