{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.212",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.212.jar",
          "url": "plugin-4.0.212.jar",
          "size": 124191,
          "sha512": "c22f95f962bc5daff306e458233eb5d88c3bd74a31a7ccd029910098c1b5eeea4ccd6d301b0a59274f75579aa5300c3c7d62e05c5a766c382b4b3e9290ad5cb0",
          "sha256": "128f9d7f2502950f00e6736e54094b15c4453a377c5035e356832b9373c9eb84",
          "sha1": "51c54c46dfd8e23542b3cd05c38bf59a885edb6f",
          "md5": "48a6445e4635915ad7f87c44574a4b69"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.212.jar",
          "url": "plugin-4.0.212.jar",
          "size": 124191,
          "sha512": "c22f95f962bc5daff306e458233eb5d88c3bd74a31a7ccd029910098c1b5eeea4ccd6d301b0a59274f75579aa5300c3c7d62e05c5a766c382b4b3e9290ad5cb0",
          "sha256": "128f9d7f2502950f00e6736e54094b15c4453a377c5035e356832b9373c9eb84",
          "sha1": "51c54c46dfd8e23542b3cd05c38bf59a885edb6f",
          "md5": "48a6445e4635915ad7f87c44574a4b69"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
