{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.238",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.238.aar",
          "url": "Applanga-4.0.238.aar",
          "size": 413352,
          "sha512": "a7e18725afe95f603b9cf6646ad827740195e4a5454b1f7032bde095737ce7481c45c14494065493845ef887cbfee47aa9bedc85c2d6dc109036c208dedcf64d",
          "sha256": "527515f57ef80c6929c1bce5101347436ef6968b032e67c2cd16dc3af2aac592",
          "sha1": "86be0dd98ae85a92c6e294175cb8785d916dba27",
          "md5": "18e66124ca1e15fcad6c9414af623793"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.238.aar",
          "url": "Applanga-4.0.238.aar",
          "size": 413352,
          "sha512": "a7e18725afe95f603b9cf6646ad827740195e4a5454b1f7032bde095737ce7481c45c14494065493845ef887cbfee47aa9bedc85c2d6dc109036c208dedcf64d",
          "sha256": "527515f57ef80c6929c1bce5101347436ef6968b032e67c2cd16dc3af2aac592",
          "sha1": "86be0dd98ae85a92c6e294175cb8785d916dba27",
          "md5": "18e66124ca1e15fcad6c9414af623793"
        }
      ]
    }
  ]
}
