{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.210",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.210.jar",
          "url": "plugin-4.0.210.jar",
          "size": 124191,
          "sha512": "90a7fd4537ee753c180e191b5933917cdc97d1db01dae0d30940e83efab4920df12d6c4b271c930fe2105535899259f362caf304a8b4eabed272d3af68381498",
          "sha256": "fa7a4d0c440f26665c03e3d43f83fd93418a28e4d67836eb004b1b2355de9baf",
          "sha1": "c562d659a8ddca27b52c25a9dc6487605e4a3acb",
          "md5": "481e5e6bb2ceb751f295adc7a51bf42d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.210.jar",
          "url": "plugin-4.0.210.jar",
          "size": 124191,
          "sha512": "90a7fd4537ee753c180e191b5933917cdc97d1db01dae0d30940e83efab4920df12d6c4b271c930fe2105535899259f362caf304a8b4eabed272d3af68381498",
          "sha256": "fa7a4d0c440f26665c03e3d43f83fd93418a28e4d67836eb004b1b2355de9baf",
          "sha1": "c562d659a8ddca27b52c25a9dc6487605e4a3acb",
          "md5": "481e5e6bb2ceb751f295adc7a51bf42d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
