{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "3.0.153",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vriouflxbbe53ihkr72q2yqteu"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.153.aar",
          "url": "Applanga-3.0.153.aar",
          "size": 198862,
          "sha512": "0cf779586413b656ae4501cab6f066da0aa60eb27d3cecf522d2f96d24e12f875910f7c6196cefeaa6278928d88139d77865f8cd6ddd7168cf4031e6e737daa1",
          "sha256": "efabe29a7eeb4e00b94f82eebdb9767dd75b65b50dd5943b27c18464896c907b",
          "sha1": "df00c245c131583653f3a9d6e0a30ffc10cc9496",
          "md5": "63228e1b4ce69d5ba5749e86b709ff40"
        }
      ]
    },
    {
      "name": "vanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.153.aar",
          "url": "Applanga-3.0.153.aar",
          "size": 198862,
          "sha512": "0cf779586413b656ae4501cab6f066da0aa60eb27d3cecf522d2f96d24e12f875910f7c6196cefeaa6278928d88139d77865f8cd6ddd7168cf4031e6e737daa1",
          "sha256": "efabe29a7eeb4e00b94f82eebdb9767dd75b65b50dd5943b27c18464896c907b",
          "sha1": "df00c245c131583653f3a9d6e0a30ffc10cc9496",
          "md5": "63228e1b4ce69d5ba5749e86b709ff40"
        }
      ]
    }
  ]
}
