{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.201",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.201.jar",
          "url": "plugin-4.0.201.jar",
          "size": 124188,
          "sha512": "b2d7f6e26b4f51ab21529b5f0180adad3b6522a922fc328dee1e9b7396e1143a6dc012d784a6d2a4260ef0e4bf807eaaf564fc78e71f9c6aa971bcbc1a758c8b",
          "sha256": "c63d7964c3f4973c3201600e8721430b407979dc5a0ba88601d0912422c8904f",
          "sha1": "3c3499e1b2c4cc00b5c0e5a7678fbcea5616cc73",
          "md5": "f938ea7018b8cbdb971841cb2df2a1b8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.201.jar",
          "url": "plugin-4.0.201.jar",
          "size": 124188,
          "sha512": "b2d7f6e26b4f51ab21529b5f0180adad3b6522a922fc328dee1e9b7396e1143a6dc012d784a6d2a4260ef0e4bf807eaaf564fc78e71f9c6aa971bcbc1a758c8b",
          "sha256": "c63d7964c3f4973c3201600e8721430b407979dc5a0ba88601d0912422c8904f",
          "sha1": "3c3499e1b2c4cc00b5c0e5a7678fbcea5616cc73",
          "md5": "f938ea7018b8cbdb971841cb2df2a1b8"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
