{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.172",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.172.jar",
          "url": "plugin-4.0.172.jar",
          "size": 91318,
          "sha512": "6305edb7362f21585640e7dd5ad931bd6e4b219868f9f0195eaaabe63232a34fd68e0bc8a641307e5ab9c357562a3cbb80a8c50473e5fd0c0cf0bd41acd510d6",
          "sha256": "d1c113262d40671f5a48197b9d96b93535d27a9b9ade5edd1d64f1f333ad0c62",
          "sha1": "c9307d155a72b7ef6a06c759c88557361644e0aa",
          "md5": "2ac7a7916f664a17f855e23fc4e3240b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.172.jar",
          "url": "plugin-4.0.172.jar",
          "size": 91318,
          "sha512": "6305edb7362f21585640e7dd5ad931bd6e4b219868f9f0195eaaabe63232a34fd68e0bc8a641307e5ab9c357562a3cbb80a8c50473e5fd0c0cf0bd41acd510d6",
          "sha256": "d1c113262d40671f5a48197b9d96b93535d27a9b9ade5edd1d64f1f333ad0c62",
          "sha1": "c9307d155a72b7ef6a06c759c88557361644e0aa",
          "md5": "2ac7a7916f664a17f855e23fc4e3240b"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
