{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.211",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.211.jar",
          "url": "plugin-4.0.211.jar",
          "size": 124191,
          "sha512": "f1658037313d89d7370d43f3c6cd91b7c1d57a50c2400d8b4825d6c9cebff2bb7295a2199f05be6553ea0849204851b501fd6abf2647d22681f1acc554967308",
          "sha256": "109d67c2865ff72dbfa87127172e44c2580708d7e3b4540b48774522bd3f3fa0",
          "sha1": "f7e7b1590871d78b6cfa4df3aee16a1b295c31ff",
          "md5": "5fcddb72898704defb5cf1affc211256"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.211.jar",
          "url": "plugin-4.0.211.jar",
          "size": 124191,
          "sha512": "f1658037313d89d7370d43f3c6cd91b7c1d57a50c2400d8b4825d6c9cebff2bb7295a2199f05be6553ea0849204851b501fd6abf2647d22681f1acc554967308",
          "sha256": "109d67c2865ff72dbfa87127172e44c2580708d7e3b4540b48774522bd3f3fa0",
          "sha1": "f7e7b1590871d78b6cfa4df3aee16a1b295c31ff",
          "md5": "5fcddb72898704defb5cf1affc211256"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
