{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.194",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.194.jar",
          "url": "plugin-4.0.194.jar",
          "size": 121162,
          "sha512": "32a2f8efb6f9a68902d1a9009560c128a17aa81b9a9752ddc00626df6ecde2593b6ca0d24645805bd02f17a2515faf81d0d07495eb61b05c90160b90d4c5f95a",
          "sha256": "d91771ad6ae50b0ffdd58bf00e9dac2721a081377ac385a7047266046a7ec119",
          "sha1": "0b514a2ebcd91cec8506325e1dd57289ce0d9a22",
          "md5": "a0d76c6eb0beb5a9b0b51c060208739c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.194.jar",
          "url": "plugin-4.0.194.jar",
          "size": 121162,
          "sha512": "32a2f8efb6f9a68902d1a9009560c128a17aa81b9a9752ddc00626df6ecde2593b6ca0d24645805bd02f17a2515faf81d0d07495eb61b05c90160b90d4c5f95a",
          "sha256": "d91771ad6ae50b0ffdd58bf00e9dac2721a081377ac385a7047266046a7ec119",
          "sha1": "0b514a2ebcd91cec8506325e1dd57289ce0d9a22",
          "md5": "a0d76c6eb0beb5a9b0b51c060208739c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
