{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.215",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.215.jar",
          "url": "plugin-4.0.215.jar",
          "size": 124583,
          "sha512": "2a9695a002f052b06707a9a183ad6cb04b63e614cdd3ec52ee602842332d3fac2dc5ac6a340c0bdbd670af034853d9ac0f3a1e828ef89894c8fad88ab41ce4cf",
          "sha256": "2de40bf7b80fdcf21b4c8e4a0d37de6ca64eb6ddb8794e7b5958cd7ae8f2ae73",
          "sha1": "3d1e2049c3efb63a1849929fcb3e6802313e99a3",
          "md5": "33bb385121101093011c3f3d8f334d11"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.215.jar",
          "url": "plugin-4.0.215.jar",
          "size": 124583,
          "sha512": "2a9695a002f052b06707a9a183ad6cb04b63e614cdd3ec52ee602842332d3fac2dc5ac6a340c0bdbd670af034853d9ac0f3a1e828ef89894c8fad88ab41ce4cf",
          "sha256": "2de40bf7b80fdcf21b4c8e4a0d37de6ca64eb6ddb8794e7b5958cd7ae8f2ae73",
          "sha1": "3d1e2049c3efb63a1849929fcb3e6802313e99a3",
          "md5": "33bb385121101093011c3f3d8f334d11"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
