{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.173",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseVariantVanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.173.aar",
          "url": "Applanga-4.0.173.aar",
          "size": 228634,
          "sha512": "25b8bb9ffa172c5c12288f8b61961993937425dd26f56acb14cffce5630e0e53aeafd931f4652675ca285dcf3973a91a523c3483191e9991c02c92ebf860e90d",
          "sha256": "9498d2a03093d85370407a052f5e6df2f6d50c0c3ca995ffe406e3596ee6c3a4",
          "sha1": "51d940685e9adb1f6c295a0e3d875eec76bd9d50",
          "md5": "523258e1b081bd60f4d03f75c1334f02"
        }
      ]
    },
    {
      "name": "vanillaReleaseVariantVanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.173.aar",
          "url": "Applanga-4.0.173.aar",
          "size": 228634,
          "sha512": "25b8bb9ffa172c5c12288f8b61961993937425dd26f56acb14cffce5630e0e53aeafd931f4652675ca285dcf3973a91a523c3483191e9991c02c92ebf860e90d",
          "sha256": "9498d2a03093d85370407a052f5e6df2f6d50c0c3ca995ffe406e3596ee6c3a4",
          "sha1": "51d940685e9adb1f6c295a0e3d875eec76bd9d50",
          "md5": "523258e1b081bd60f4d03f75c1334f02"
        }
      ]
    }
  ]
}
