{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.145",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "lgvut5qmxfdkpat5oo6qwsrxom"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.145.jar",
          "url": "plugin-3.0.145.jar",
          "size": 130464,
          "sha512": "f5a5b769159a90457306114a1a712d192050c517b34d50b921f36ecda2dbeb25ba26bc38fa4a6e2eb82546df0f43a3a7c31d1e2a7e95209771576c9b0d6fdb54",
          "sha256": "9297875d045c2ef25bce27bf4caf45c22bc4687f9f66208923467cc6d8b2b938",
          "sha1": "32365777958e305f1ff0a72ad392ba4c0ae2ae8e",
          "md5": "9c2d44e16a448621d5841d0571b9ff0e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.145.jar",
          "url": "plugin-3.0.145.jar",
          "size": 130464,
          "sha512": "f5a5b769159a90457306114a1a712d192050c517b34d50b921f36ecda2dbeb25ba26bc38fa4a6e2eb82546df0f43a3a7c31d1e2a7e95209771576c9b0d6fdb54",
          "sha256": "9297875d045c2ef25bce27bf4caf45c22bc4687f9f66208923467cc6d8b2b938",
          "sha1": "32365777958e305f1ff0a72ad392ba4c0ae2ae8e",
          "md5": "9c2d44e16a448621d5841d0571b9ff0e"
        }
      ]
    }
  ]
}
