{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.195",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.195.jar",
          "url": "plugin-4.0.195.jar",
          "size": 121162,
          "sha512": "f535bc726f02beb07de8beb27d801188aac6f1b1bda97f85dc3a276a5523c1779777025e309198131687babea5c19b4f07cf310fe68b9e31ab6213ee53871676",
          "sha256": "599c47f5838c2714ff54a39f783323c7b57fe28a0434d122c1f3dac73037ee29",
          "sha1": "983466b1b09b9d84be0d9d1fbd9f6c1bf8a6b07b",
          "md5": "761b1b196b6eb9d9a92985081d836077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.195.jar",
          "url": "plugin-4.0.195.jar",
          "size": 121162,
          "sha512": "f535bc726f02beb07de8beb27d801188aac6f1b1bda97f85dc3a276a5523c1779777025e309198131687babea5c19b4f07cf310fe68b9e31ab6213ee53871676",
          "sha256": "599c47f5838c2714ff54a39f783323c7b57fe28a0434d122c1f3dac73037ee29",
          "sha1": "983466b1b09b9d84be0d9d1fbd9f6c1bf8a6b07b",
          "md5": "761b1b196b6eb9d9a92985081d836077"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
