{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.235",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.235.aar",
          "url": "Applanga-4.0.235.aar",
          "size": 413362,
          "sha512": "490f6c481e52b18eb89af481354cca0f8e9ac6fa8d1925508ddd680b3c8a1aac571426c8d643307e289ab0445bc2369ed21ed5e90f90b9281baaf92eedb2235a",
          "sha256": "d759c2b536cd7b06c0f1bb5131b2cb4d38ff10b59a77aae1c44e58d4bbd83a8b",
          "sha1": "00269a07d687dc006e7bfa48b01ffbf55c0243b5",
          "md5": "c11cc4ce9cc74d52aeda09262ce6d841"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.235.aar",
          "url": "Applanga-4.0.235.aar",
          "size": 413362,
          "sha512": "490f6c481e52b18eb89af481354cca0f8e9ac6fa8d1925508ddd680b3c8a1aac571426c8d643307e289ab0445bc2369ed21ed5e90f90b9281baaf92eedb2235a",
          "sha256": "d759c2b536cd7b06c0f1bb5131b2cb4d38ff10b59a77aae1c44e58d4bbd83a8b",
          "sha1": "00269a07d687dc006e7bfa48b01ffbf55c0243b5",
          "md5": "c11cc4ce9cc74d52aeda09262ce6d841"
        }
      ]
    }
  ]
}
