{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.177",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.177.jar",
          "url": "plugin-4.0.177.jar",
          "size": 93870,
          "sha512": "9085e5e6cb2b253fdbf6d3d0fb3ca9a1281b5bb9c5b5221d71a1a2dcc2b5af12787e2649675e3a3138711448c124a9f375c6561b2d9a2fabdc4e59b09e88545b",
          "sha256": "c437fb0efd5848963aea3b2ea54168771f81e9b24a5402790f203b6c22767cda",
          "sha1": "d94febda20a9efd2cda9c5f5cf29478e75acd8c8",
          "md5": "7fd768cf31a9fc9a6347a8273cc19faa"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.177.jar",
          "url": "plugin-4.0.177.jar",
          "size": 93870,
          "sha512": "9085e5e6cb2b253fdbf6d3d0fb3ca9a1281b5bb9c5b5221d71a1a2dcc2b5af12787e2649675e3a3138711448c124a9f375c6561b2d9a2fabdc4e59b09e88545b",
          "sha256": "c437fb0efd5848963aea3b2ea54168771f81e9b24a5402790f203b6c22767cda",
          "sha1": "d94febda20a9efd2cda9c5f5cf29478e75acd8c8",
          "md5": "7fd768cf31a9fc9a6347a8273cc19faa"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
