{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.220",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.220.jar",
          "url": "plugin-4.0.220.jar",
          "size": 140077,
          "sha512": "52b02ed84b9f897d3075e3ea281b98146098ad91dbe533b26e16797d680e88b38cd92407f1093d4afa43e4877db002c42aa9ce8025b087fe398bfc4ce5a163f5",
          "sha256": "e4fc6fe36a7a5725f7a0812d5c8ab01993be60c51c7df07931c23107b9b97ff3",
          "sha1": "aa5aa78e8e24debd2b971f003fa7f40af6ebe3a9",
          "md5": "703087c2fa052b29a16b4cbb11202965"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.220.jar",
          "url": "plugin-4.0.220.jar",
          "size": 140077,
          "sha512": "52b02ed84b9f897d3075e3ea281b98146098ad91dbe533b26e16797d680e88b38cd92407f1093d4afa43e4877db002c42aa9ce8025b087fe398bfc4ce5a163f5",
          "sha256": "e4fc6fe36a7a5725f7a0812d5c8ab01993be60c51c7df07931c23107b9b97ff3",
          "sha1": "aa5aa78e8e24debd2b971f003fa7f40af6ebe3a9",
          "md5": "703087c2fa052b29a16b4cbb11202965"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
