{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.226",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.226.jar",
          "url": "plugin-4.0.226.jar",
          "size": 144474,
          "sha512": "539fbc3b3ad93daf7f7d09bb42b60fe6fd65320cb1d539b453b6ce917b4400e8a8e869555914f72e696f02415d6854d69be1cead4ea87255be467a85aaebb74d",
          "sha256": "38f4ef7f3d0761c25242e6c4af68753aa53b9a908019ef80308f1b83b7f14174",
          "sha1": "51e774f37c007b25bf04eb815510f964705e8365",
          "md5": "a84791a1b8b535a6fe3b7a7e3f2be4b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.226.jar",
          "url": "plugin-4.0.226.jar",
          "size": 144474,
          "sha512": "539fbc3b3ad93daf7f7d09bb42b60fe6fd65320cb1d539b453b6ce917b4400e8a8e869555914f72e696f02415d6854d69be1cead4ea87255be467a85aaebb74d",
          "sha256": "38f4ef7f3d0761c25242e6c4af68753aa53b9a908019ef80308f1b83b7f14174",
          "sha1": "51e774f37c007b25bf04eb815510f964705e8365",
          "md5": "a84791a1b8b535a6fe3b7a7e3f2be4b9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
