{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.158",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "4rv333aptzf2tdav7h7ixysxxy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.158.jar",
          "url": "plugin-3.0.158.jar",
          "size": 151665,
          "sha512": "23092af1a4b77ca6701dd7b741352d4e09eb9323edc9b79a0c3b1ed79087dec4272b77d4e042d22f2b6ac3ffc7f4e4c6986d39c006f8af8001748ee98ecbf78f",
          "sha256": "db855c1070dbe710dc8d6da160414e139e2ac13c08e6d8c1ca5fc98f820f5ffc",
          "sha1": "be283af9bfcba165804a3cce2f156ef9410a4001",
          "md5": "b85b31ed404cf9b394331e9f3579ae52"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.158.jar",
          "url": "plugin-3.0.158.jar",
          "size": 151665,
          "sha512": "23092af1a4b77ca6701dd7b741352d4e09eb9323edc9b79a0c3b1ed79087dec4272b77d4e042d22f2b6ac3ffc7f4e4c6986d39c006f8af8001748ee98ecbf78f",
          "sha256": "db855c1070dbe710dc8d6da160414e139e2ac13c08e6d8c1ca5fc98f820f5ffc",
          "sha1": "be283af9bfcba165804a3cce2f156ef9410a4001",
          "md5": "b85b31ed404cf9b394331e9f3579ae52"
        }
      ]
    }
  ]
}
