{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.178",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.178.jar",
          "url": "plugin-4.0.178.jar",
          "size": 93870,
          "sha512": "00723ed42cf93932ea55b94ce38cb211814cca5e6c7fd0cd6902d99db178b59d04c78635a4638db809b49f4fefd4eead408bcd21c63dd08e6ec86eda76956318",
          "sha256": "1fd3789eebe8db7091a3246ee3f6eeb974fae77095193e2ac4337b19767e41f6",
          "sha1": "af9620d3ee2caa532c7f8aac1b2ee6e2ea455d47",
          "md5": "b0fd6ac439919475244b4d90ce509e64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.178.jar",
          "url": "plugin-4.0.178.jar",
          "size": 93870,
          "sha512": "00723ed42cf93932ea55b94ce38cb211814cca5e6c7fd0cd6902d99db178b59d04c78635a4638db809b49f4fefd4eead408bcd21c63dd08e6ec86eda76956318",
          "sha256": "1fd3789eebe8db7091a3246ee3f6eeb974fae77095193e2ac4337b19767e41f6",
          "sha1": "af9620d3ee2caa532c7f8aac1b2ee6e2ea455d47",
          "md5": "b0fd6ac439919475244b4d90ce509e64"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
