{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.140",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "b7igb36ww5h4ta3efjvhzrtfo4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.140.jar",
          "url": "plugin-3.0.140.jar",
          "size": 123012,
          "sha512": "da9b3dfb4d5df073651ceecaffbb132d4dc3092193ea14a6d4dd534e074051e05e5d475778a07c1e8bf38a0ec9aae395e3d9de6d02cfe8ca6dd220d7fd86e156",
          "sha256": "edd72cbd542113f520e3c66f225c353f59124cb57dc4c7bd3190ff8ddb9dcb3a",
          "sha1": "d1090d817199057928c2bc974fae9a69893f6e3b",
          "md5": "ad73cae9937318b902d0a6c4f90a4bb5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.140.jar",
          "url": "plugin-3.0.140.jar",
          "size": 123012,
          "sha512": "da9b3dfb4d5df073651ceecaffbb132d4dc3092193ea14a6d4dd534e074051e05e5d475778a07c1e8bf38a0ec9aae395e3d9de6d02cfe8ca6dd220d7fd86e156",
          "sha256": "edd72cbd542113f520e3c66f225c353f59124cb57dc4c7bd3190ff8ddb9dcb3a",
          "sha1": "d1090d817199057928c2bc974fae9a69893f6e3b",
          "md5": "ad73cae9937318b902d0a6c4f90a4bb5"
        }
      ]
    }
  ]
}
