{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.150",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "vcpoqzb345coxam6ylwx77vuoi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.150.jar",
          "url": "plugin-3.0.150.jar",
          "size": 137402,
          "sha512": "a7fff4ad8243b555bbeb5b13f3ce6580cb191915f0d1694dedd2f2fcaa43ec3152c2dfc0a23c8c1ffd7fb4ad62b8e37a821dd84f44813c952e4d1c76e6a10ea1",
          "sha256": "fe8a131d6b61c435a244e1c541a1602feef932550a456705c49b24bbaea2d7dd",
          "sha1": "9aa710edc5e2fb2ed74de1d4f2f24103e5c8a8aa",
          "md5": "25a852d33c688c0f18018b9e6344662a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.150.jar",
          "url": "plugin-3.0.150.jar",
          "size": 137402,
          "sha512": "a7fff4ad8243b555bbeb5b13f3ce6580cb191915f0d1694dedd2f2fcaa43ec3152c2dfc0a23c8c1ffd7fb4ad62b8e37a821dd84f44813c952e4d1c76e6a10ea1",
          "sha256": "fe8a131d6b61c435a244e1c541a1602feef932550a456705c49b24bbaea2d7dd",
          "sha1": "9aa710edc5e2fb2ed74de1d4f2f24103e5c8a8aa",
          "md5": "25a852d33c688c0f18018b9e6344662a"
        }
      ]
    }
  ]
}
