{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.239",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.239.jar",
          "url": "plugin-4.0.239.jar",
          "size": 144826,
          "sha512": "800c4cf74fb8fed6985f54a8f1b8cdc6867bcd47b956043a23f5b63486520f27b22381ddd9118cceac032978af3f95a2ac016ab26afadda0abac32d66a9202b4",
          "sha256": "0319a4015b267cc3d99fe6e5b8675cff5deb1c502b6d034a58d6c87d7a2a26e3",
          "sha1": "686e04b979499cc8fe86f8b98fa2cc255d0e9d43",
          "md5": "fe509eb289494903519d7ab6de86bae1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.239.jar",
          "url": "plugin-4.0.239.jar",
          "size": 144826,
          "sha512": "800c4cf74fb8fed6985f54a8f1b8cdc6867bcd47b956043a23f5b63486520f27b22381ddd9118cceac032978af3f95a2ac016ab26afadda0abac32d66a9202b4",
          "sha256": "0319a4015b267cc3d99fe6e5b8675cff5deb1c502b6d034a58d6c87d7a2a26e3",
          "sha1": "686e04b979499cc8fe86f8b98fa2cc255d0e9d43",
          "md5": "fe509eb289494903519d7ab6de86bae1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
