{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.136",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zbasi5n6ife2vevshoqpfnesfe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.136.jar",
          "url": "plugin-3.0.136.jar",
          "size": 122643,
          "sha512": "66e2966c910cb3b3ef3abd83d881748af370e472121d4c18849e5fa69d8afca410056fccd45f6d610d7cdabe25d836deefcf0dfa43b88c48fb7763787dd2b253",
          "sha256": "54e383657d9fa839d00b6825cd0633f9fa8e50641dfe35ce8099bda02da5984d",
          "sha1": "5c5526f94ff4828424b143a292cd0c6326a6a94a",
          "md5": "a79d8a7d6962f0e22b5691cdd82643ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.136.jar",
          "url": "plugin-3.0.136.jar",
          "size": 122643,
          "sha512": "66e2966c910cb3b3ef3abd83d881748af370e472121d4c18849e5fa69d8afca410056fccd45f6d610d7cdabe25d836deefcf0dfa43b88c48fb7763787dd2b253",
          "sha256": "54e383657d9fa839d00b6825cd0633f9fa8e50641dfe35ce8099bda02da5984d",
          "sha1": "5c5526f94ff4828424b143a292cd0c6326a6a94a",
          "md5": "a79d8a7d6962f0e22b5691cdd82643ea"
        }
      ]
    }
  ]
}
