{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.234",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.234.jar",
          "url": "plugin-4.0.234.jar",
          "size": 144827,
          "sha512": "2d6750bec7965d2796b1f74380329c602819891e05c253754707e98e5d271ca3f98fa7f2c55994d4514aa9cd41e9163b10802b081b9761ce7a2ab61c8a843a9e",
          "sha256": "209491e015911bb9e4099aadd6b590d9ac9716d2d9d8a6ecee98bc8610f2607c",
          "sha1": "87fa6692bf6c5bb6003ffd6581b20d5b821e4d64",
          "md5": "9082dcbe03aca828dd382103fdc9f1d9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.234.jar",
          "url": "plugin-4.0.234.jar",
          "size": 144827,
          "sha512": "2d6750bec7965d2796b1f74380329c602819891e05c253754707e98e5d271ca3f98fa7f2c55994d4514aa9cd41e9163b10802b081b9761ce7a2ab61c8a843a9e",
          "sha256": "209491e015911bb9e4099aadd6b590d9ac9716d2d9d8a6ecee98bc8610f2607c",
          "sha1": "87fa6692bf6c5bb6003ffd6581b20d5b821e4d64",
          "md5": "9082dcbe03aca828dd382103fdc9f1d9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
