{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.189",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.189.jar",
          "url": "plugin-4.0.189.jar",
          "size": 120431,
          "sha512": "1381f3e7357e3abd6f327981d3e199d3543f2cd66edbfabf830009ab990dafaa45519ce6c68a3461b9ce4a67da388acbacecc5c3e9b3595fe3398e481ed15192",
          "sha256": "b4f31aba2c9c53223223e9ad6182c278dbad09b32056a1d96bab1e201fca80c7",
          "sha1": "55870f7cc4511d544d993b61e81f1ab28d63a5ce",
          "md5": "031568d584b249cfa5f5b9fd3ddf3ecd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.189.jar",
          "url": "plugin-4.0.189.jar",
          "size": 120431,
          "sha512": "1381f3e7357e3abd6f327981d3e199d3543f2cd66edbfabf830009ab990dafaa45519ce6c68a3461b9ce4a67da388acbacecc5c3e9b3595fe3398e481ed15192",
          "sha256": "b4f31aba2c9c53223223e9ad6182c278dbad09b32056a1d96bab1e201fca80c7",
          "sha1": "55870f7cc4511d544d993b61e81f1ab28d63a5ce",
          "md5": "031568d584b249cfa5f5b9fd3ddf3ecd"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
