{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.229",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.229.jar",
          "url": "plugin-4.0.229.jar",
          "size": 144826,
          "sha512": "3cb969860a0131ed4469117e51a6a9c49c552fb7f5d0b3b85d6e357a2f33f358a3303b036ab8bef92adece6cea84d24a1dc94d62c4c7c6dd93ed54462ab15558",
          "sha256": "27bc0c7d42fea5af3546c2d2b00adf76d3079fc13694159bca1c9d0ad8f873b9",
          "sha1": "c1beab6d650df16f3586fc3a20a16de45bf9ef76",
          "md5": "812384904ac157ccdf433de77e77097d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.229.jar",
          "url": "plugin-4.0.229.jar",
          "size": 144826,
          "sha512": "3cb969860a0131ed4469117e51a6a9c49c552fb7f5d0b3b85d6e357a2f33f358a3303b036ab8bef92adece6cea84d24a1dc94d62c4c7c6dd93ed54462ab15558",
          "sha256": "27bc0c7d42fea5af3546c2d2b00adf76d3079fc13694159bca1c9d0ad8f873b9",
          "sha1": "c1beab6d650df16f3586fc3a20a16de45bf9ef76",
          "md5": "812384904ac157ccdf433de77e77097d"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
