{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.213",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.213.jar",
          "url": "plugin-4.0.213.jar",
          "size": 124201,
          "sha512": "e337fd91e9907e01164682493b8f33b6950f45ece56f204b4b5552939ffcfc3645d0fcac9b3c36425cbfce75efbde2b35a6bf2229affd6c3f149c166d24dbc08",
          "sha256": "56b5243e9b391165dd615fcc67a8704c8cc67cdda73ab65a1ee486dc46161128",
          "sha1": "a4900e4d29d17668ed68b5506fed7884b289aaf6",
          "md5": "bf87954d9e46335017e89b8cff4eb6de"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.213.jar",
          "url": "plugin-4.0.213.jar",
          "size": 124201,
          "sha512": "e337fd91e9907e01164682493b8f33b6950f45ece56f204b4b5552939ffcfc3645d0fcac9b3c36425cbfce75efbde2b35a6bf2229affd6c3f149c166d24dbc08",
          "sha256": "56b5243e9b391165dd615fcc67a8704c8cc67cdda73ab65a1ee486dc46161128",
          "sha1": "a4900e4d29d17668ed68b5506fed7884b289aaf6",
          "md5": "bf87954d9e46335017e89b8cff4eb6de"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
