{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.193",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.193.jar",
          "url": "plugin-4.0.193.jar",
          "size": 121161,
          "sha512": "56addcf2ddc8d9fc96c2ba5ec2e00eb5a01abd0d66df4ff0272a59a90bed95eca95ef6089012909c5b3a739a7c36875447ba64ab651d7863a0cce9366070cf8e",
          "sha256": "87b95248e0959fe67c033b155a75ed0f74f997d0f5a0dd64abc35aa7502fa5fe",
          "sha1": "22f0f233184b4d34cc06462f8b4ffcb78f7de20a",
          "md5": "ecc669f2715634b26f31c31a5f229fa4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.193.jar",
          "url": "plugin-4.0.193.jar",
          "size": 121161,
          "sha512": "56addcf2ddc8d9fc96c2ba5ec2e00eb5a01abd0d66df4ff0272a59a90bed95eca95ef6089012909c5b3a739a7c36875447ba64ab651d7863a0cce9366070cf8e",
          "sha256": "87b95248e0959fe67c033b155a75ed0f74f997d0f5a0dd64abc35aa7502fa5fe",
          "sha1": "22f0f233184b4d34cc06462f8b4ffcb78f7de20a",
          "md5": "ecc669f2715634b26f31c31a5f229fa4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
