{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.220",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.220.aar",
          "url": "Applanga-4.0.220.aar",
          "size": 386888,
          "sha512": "9c8ee3548ddb62d9a9f268f3dff07d0ec42fe1be02d3c2b71417c2c9efa2a8ee66617891a22adc08fafa255a37fb5a2c1a9964fb757dbc33805db38be88532ac",
          "sha256": "310d46e6e9c6a0b41095c53230ae558389b84baef992087b297fd3376c4592fc",
          "sha1": "28c24cc9b36e931662318da761ca2a56ccefa152",
          "md5": "1002fa7ad449dd77cbac2310687ca9c6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.220.aar",
          "url": "Applanga-4.0.220.aar",
          "size": 386888,
          "sha512": "9c8ee3548ddb62d9a9f268f3dff07d0ec42fe1be02d3c2b71417c2c9efa2a8ee66617891a22adc08fafa255a37fb5a2c1a9964fb757dbc33805db38be88532ac",
          "sha256": "310d46e6e9c6a0b41095c53230ae558389b84baef992087b297fd3376c4592fc",
          "sha1": "28c24cc9b36e931662318da761ca2a56ccefa152",
          "md5": "1002fa7ad449dd77cbac2310687ca9c6"
        }
      ]
    }
  ]
}
