{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.209",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.209.jar",
          "url": "plugin-4.0.209.jar",
          "size": 124192,
          "sha512": "bd1ba0336bdf7e30d3202000d9f8102d7067fb6af2242efd666910efe7a510d753c035e7c06f59da4f1af1c0939d9afe0c4f0249e4474b5d91ee650b9dc65425",
          "sha256": "51cc4c8f9d3cec3294f6f325d206338fd52626ffc28b6080a80e214dc91bb786",
          "sha1": "621ba49d4ba05d32a8854e9df8d4c5be696dda1f",
          "md5": "60d31813efd4c35b09101b0fef3ed354"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.209.jar",
          "url": "plugin-4.0.209.jar",
          "size": 124192,
          "sha512": "bd1ba0336bdf7e30d3202000d9f8102d7067fb6af2242efd666910efe7a510d753c035e7c06f59da4f1af1c0939d9afe0c4f0249e4474b5d91ee650b9dc65425",
          "sha256": "51cc4c8f9d3cec3294f6f325d206338fd52626ffc28b6080a80e214dc91bb786",
          "sha1": "621ba49d4ba05d32a8854e9df8d4c5be696dda1f",
          "md5": "60d31813efd4c35b09101b0fef3ed354"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
