{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "3.0.167",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "463jokwwgfetxno7fi6xtek5e4"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.167.aar",
          "url": "Applanga-3.0.167.aar",
          "size": 200842,
          "sha512": "2193f6909bcab54c389a180eb14fdb09b3763215926ecfe23eb43c79f144933dde1f837aa58c08007d2a8917f0a65887ce532750fc3f4f0742e35a8cd78b4638",
          "sha256": "5f196e5fff729e51ca8f0b00ab2e19489accc871f7e6c85b9afa45ebc9b2aaf1",
          "sha1": "05c6f3d3585e381f075c5ffad211b5cf7ee99ac6",
          "md5": "0f6794ee9785df4fecef4f8ca8b3f729"
        }
      ]
    },
    {
      "name": "vanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.167.aar",
          "url": "Applanga-3.0.167.aar",
          "size": 200842,
          "sha512": "2193f6909bcab54c389a180eb14fdb09b3763215926ecfe23eb43c79f144933dde1f837aa58c08007d2a8917f0a65887ce532750fc3f4f0742e35a8cd78b4638",
          "sha256": "5f196e5fff729e51ca8f0b00ab2e19489accc871f7e6c85b9afa45ebc9b2aaf1",
          "sha1": "05c6f3d3585e381f075c5ffad211b5cf7ee99ac6",
          "md5": "0f6794ee9785df4fecef4f8ca8b3f729"
        }
      ]
    }
  ]
}
