{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.156",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "l4sak5ueg5daxekfiqqiqsgzai"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.156.jar",
          "url": "plugin-3.0.156.jar",
          "size": 151665,
          "sha512": "786dba4f5b3a5adb475d96d154e06756d0d0d47318d909c0c2439ab23d2c4a09126a3ededa17eca7ac59860e0c28576631fc64c2c3b9eae552d2943d94436f4c",
          "sha256": "109730ea82208edde737c5110f2be0fbd077125fe374b2ec630bf7d21ce18995",
          "sha1": "7004e5008d1174ec7260a4f825dc4f59158b97de",
          "md5": "4b5f49e111209ce2c4422af6a0824192"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.156.jar",
          "url": "plugin-3.0.156.jar",
          "size": 151665,
          "sha512": "786dba4f5b3a5adb475d96d154e06756d0d0d47318d909c0c2439ab23d2c4a09126a3ededa17eca7ac59860e0c28576631fc64c2c3b9eae552d2943d94436f4c",
          "sha256": "109730ea82208edde737c5110f2be0fbd077125fe374b2ec630bf7d21ce18995",
          "sha1": "7004e5008d1174ec7260a4f825dc4f59158b97de",
          "md5": "4b5f49e111209ce2c4422af6a0824192"
        }
      ]
    }
  ]
}
