{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "3.0.158",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "oz7dsxojzbfgpkjslbs3ulomha"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.158.aar",
          "url": "Applanga-3.0.158.aar",
          "size": 198785,
          "sha512": "c136d7e3188710bd80636df1469262d0eee92789abf8d293a3d7be4f52adddde7705cf87fc6c4e7706ea368dbd5decb0fa439fae46fce03e829778f458d74959",
          "sha256": "80b32639d42b64300ccb7d909ea6331a9e44557dfa672d81e49a322277a33c92",
          "sha1": "a2a8f80d6217024b8809d550c0ff6ff0be959e41",
          "md5": "c4150717d9705a052f1abefcbed15d90"
        }
      ]
    },
    {
      "name": "vanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.158.aar",
          "url": "Applanga-3.0.158.aar",
          "size": 198785,
          "sha512": "c136d7e3188710bd80636df1469262d0eee92789abf8d293a3d7be4f52adddde7705cf87fc6c4e7706ea368dbd5decb0fa439fae46fce03e829778f458d74959",
          "sha256": "80b32639d42b64300ccb7d909ea6331a9e44557dfa672d81e49a322277a33c92",
          "sha1": "a2a8f80d6217024b8809d550c0ff6ff0be959e41",
          "md5": "c4150717d9705a052f1abefcbed15d90"
        }
      ]
    }
  ]
}
