{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.135",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "wiwlcrdmozbrtbmqoy37gg4gka"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.135.jar",
          "url": "plugin-3.0.135.jar",
          "size": 122644,
          "sha512": "cb06a205ac3316c78ad60da62448c397b8b93852487ec932d14260f21fe764663e7677b8f7d688b6ed1399cbf7a852ccfe239b554d5204ded132da6f3b576771",
          "sha256": "949cfbe4fa4715aabcd6fbba4733415807e1dd12961f6d2512d35fdf375880b1",
          "sha1": "bdadf427c095f12e65683a268fd7fb3971e35543",
          "md5": "36c97983d05261f12ef8fc7e6b077d21"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.135.jar",
          "url": "plugin-3.0.135.jar",
          "size": 122644,
          "sha512": "cb06a205ac3316c78ad60da62448c397b8b93852487ec932d14260f21fe764663e7677b8f7d688b6ed1399cbf7a852ccfe239b554d5204ded132da6f3b576771",
          "sha256": "949cfbe4fa4715aabcd6fbba4733415807e1dd12961f6d2512d35fdf375880b1",
          "sha1": "bdadf427c095f12e65683a268fd7fb3971e35543",
          "md5": "36c97983d05261f12ef8fc7e6b077d21"
        }
      ]
    }
  ]
}
