{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.183",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.183.jar",
          "url": "plugin-4.0.183.jar",
          "size": 103283,
          "sha512": "8b3f97860dec88db399ed2ec62f654f4262bcb77d48a86d9909f0c5593347e01079ea866518c1067a88052a4022d5326b76e4559b8d53badbe5c00e8f8b3ff44",
          "sha256": "8f01c0e6b815bbb46b7113a321781cfc91e3189d763eb7fb24f24023dc35209a",
          "sha1": "187236ca84dce333fd6d3295fff8ba7d2667b7f4",
          "md5": "6c427eff49c822168536b44275ef6223"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.183.jar",
          "url": "plugin-4.0.183.jar",
          "size": 103283,
          "sha512": "8b3f97860dec88db399ed2ec62f654f4262bcb77d48a86d9909f0c5593347e01079ea866518c1067a88052a4022d5326b76e4559b8d53badbe5c00e8f8b3ff44",
          "sha256": "8f01c0e6b815bbb46b7113a321781cfc91e3189d763eb7fb24f24023dc35209a",
          "sha1": "187236ca84dce333fd6d3295fff8ba7d2667b7f4",
          "md5": "6c427eff49c822168536b44275ef6223"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
