{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.238",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.238.jar",
          "url": "plugin-4.0.238.jar",
          "size": 144826,
          "sha512": "36376d0c4d22b205377ed6194afae5db0167180c173175562ef7ec211cd7d1f7c20ea9ded42c7210764b6d199ad034fcc05e2c5a95ba01e375a4d1715f79d4dc",
          "sha256": "e2e1fe342f7b341c9e9735f1a077532f5c81c8956ea34e96d28450cdaff4a9bd",
          "sha1": "553fc0accaad9a03f71383174791b3fc718d3b8d",
          "md5": "76b7db5961f97288d811ed4d1a7ac112"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.238.jar",
          "url": "plugin-4.0.238.jar",
          "size": 144826,
          "sha512": "36376d0c4d22b205377ed6194afae5db0167180c173175562ef7ec211cd7d1f7c20ea9ded42c7210764b6d199ad034fcc05e2c5a95ba01e375a4d1715f79d4dc",
          "sha256": "e2e1fe342f7b341c9e9735f1a077532f5c81c8956ea34e96d28450cdaff4a9bd",
          "sha1": "553fc0accaad9a03f71383174791b3fc718d3b8d",
          "md5": "76b7db5961f97288d811ed4d1a7ac112"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
