{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.179",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.179.jar",
          "url": "plugin-4.0.179.jar",
          "size": 97886,
          "sha512": "7c468d8e6b7f0159ef6355e6f39aa679f47b925814ab1688341801bbec7f44713d2d993fc7d038946d2f5fa4e6de435f6735edf0262e62421050fd67ce13debd",
          "sha256": "888dd978848d37bafb83a5187495edf71f13e490e74e30ee7b5d40d0f36ccde7",
          "sha1": "9cef73057ad8214b27c92576369f5983fe1d5ab3",
          "md5": "760fa1dc6e0afc2b890fd08145ed80a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.179.jar",
          "url": "plugin-4.0.179.jar",
          "size": 97886,
          "sha512": "7c468d8e6b7f0159ef6355e6f39aa679f47b925814ab1688341801bbec7f44713d2d993fc7d038946d2f5fa4e6de435f6735edf0262e62421050fd67ce13debd",
          "sha256": "888dd978848d37bafb83a5187495edf71f13e490e74e30ee7b5d40d0f36ccde7",
          "sha1": "9cef73057ad8214b27c92576369f5983fe1d5ab3",
          "md5": "760fa1dc6e0afc2b890fd08145ed80a3"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
