{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.208",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.208.jar",
          "url": "plugin-4.0.208.jar",
          "size": 124192,
          "sha512": "505d3c5211c23b9982d5f22dd026c182c87093ec8ec4ce4b182858707fe91a9497206aedd584eb3c9743a424c1d698e32fbf933ff8dc6a01fb869a350456620b",
          "sha256": "e1e0a8cc59b5c0ffd4fc19ac3e8a142b2fd55474b4deb5d419f62ca4569725f0",
          "sha1": "daa0640ebd772fdf5a6721bd18553634353639d3",
          "md5": "b826b733ad66ed396dafa63eb64abccb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.208.jar",
          "url": "plugin-4.0.208.jar",
          "size": 124192,
          "sha512": "505d3c5211c23b9982d5f22dd026c182c87093ec8ec4ce4b182858707fe91a9497206aedd584eb3c9743a424c1d698e32fbf933ff8dc6a01fb869a350456620b",
          "sha256": "e1e0a8cc59b5c0ffd4fc19ac3e8a142b2fd55474b4deb5d419f62ca4569725f0",
          "sha1": "daa0640ebd772fdf5a6721bd18553634353639d3",
          "md5": "b826b733ad66ed396dafa63eb64abccb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
