{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "3.0.144",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "v35zxm4fubdwfjm4dl27ftk6ey"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.144.aar",
          "url": "Applanga-3.0.144.aar",
          "size": 188668,
          "sha512": "ecdd059540eb6fb498abb3d10f002fe72997012a873c48bc478c22b555ab84507ec3bb2a06507681765bddad7ad084be60522183bbb77e313b1d1a28f54c8daa",
          "sha256": "b6e2aee776f2c568369abf3dbb26f9ba34da9289af7d1f7b3165f073968d0af1",
          "sha1": "a526d0d598bd197d1a82397c2789d846b37e886e",
          "md5": "ba18ccae0133a4cb2c77ba6dceadda85"
        }
      ]
    },
    {
      "name": "vanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.1.1"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-3.0.144.aar",
          "url": "Applanga-3.0.144.aar",
          "size": 188668,
          "sha512": "ecdd059540eb6fb498abb3d10f002fe72997012a873c48bc478c22b555ab84507ec3bb2a06507681765bddad7ad084be60522183bbb77e313b1d1a28f54c8daa",
          "sha256": "b6e2aee776f2c568369abf3dbb26f9ba34da9289af7d1f7b3165f073968d0af1",
          "sha1": "a526d0d598bd197d1a82397c2789d846b37e886e",
          "md5": "ba18ccae0133a4cb2c77ba6dceadda85"
        }
      ]
    }
  ]
}
