{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.236",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.236.aar",
          "url": "Applanga-4.0.236.aar",
          "size": 413333,
          "sha512": "784559d09558efe901f399991a18259fd1946e89bc40b6f4efaf0e01c117232fdacae27b6983055bdfa28718a9a32954e62eaa217f9b85ed28958e7f2e261136",
          "sha256": "4066c3c79ac78771d21a18e9c02e2ac4554a67fb5ad4e44a229549c9bff5d02f",
          "sha1": "5488f87ae80ab4cc734bd191c211d8e32afa294b",
          "md5": "cd9940255d5e63876e34cbbb7626f146"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.236.aar",
          "url": "Applanga-4.0.236.aar",
          "size": 413333,
          "sha512": "784559d09558efe901f399991a18259fd1946e89bc40b6f4efaf0e01c117232fdacae27b6983055bdfa28718a9a32954e62eaa217f9b85ed28958e7f2e261136",
          "sha256": "4066c3c79ac78771d21a18e9c02e2ac4554a67fb5ad4e44a229549c9bff5d02f",
          "sha1": "5488f87ae80ab4cc734bd191c211d8e32afa294b",
          "md5": "cd9940255d5e63876e34cbbb7626f146"
        }
      ]
    }
  ]
}
