{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.157",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "cccdpdeorzgdhlqsbyvv5ld74q"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.157.jar",
          "url": "plugin-3.0.157.jar",
          "size": 151665,
          "sha512": "7ce73981b4a54fc6e05ec9f64e55c80cd1b1ecf8f52c2f8497d340ff8f035af400dd8ccb33b49cee9e34ed99117930494d89712e5f49056d3f77287212568fde",
          "sha256": "4fcd8208c15395a045cc46bd01dc5594ebc44f7b4dad9b1dc579fec355c1ed31",
          "sha1": "b7878112d7913dc705d64b0f5779ab9ba8d6c63c",
          "md5": "f84738d0caca8b90bb9c6d0132fbb81d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.157.jar",
          "url": "plugin-3.0.157.jar",
          "size": 151665,
          "sha512": "7ce73981b4a54fc6e05ec9f64e55c80cd1b1ecf8f52c2f8497d340ff8f035af400dd8ccb33b49cee9e34ed99117930494d89712e5f49056d3f77287212568fde",
          "sha256": "4fcd8208c15395a045cc46bd01dc5594ebc44f7b4dad9b1dc579fec355c1ed31",
          "sha1": "b7878112d7913dc705d64b0f5779ab9ba8d6c63c",
          "md5": "f84738d0caca8b90bb9c6d0132fbb81d"
        }
      ]
    }
  ]
}
