{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.170",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.170.jar",
          "url": "plugin-4.0.170.jar",
          "size": 86156,
          "sha512": "acbc3661a8c55006a59e03f2c9cf3497592bebad5a4ac49a8dceef0aabed4812cc93d6974f98c9b861690b1147eac1c03af2c038cddf6eff65eb54ccf7a16bdc",
          "sha256": "c55fcb368e212e53e3c5acf31fb7995867d4dbc9cdfaaca9b70bdbe8fa7af317",
          "sha1": "b5e1dc9218ce773d569e712dd33e5b5650bcf746",
          "md5": "9cc961f22736f805e66882339714cc49"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.170.jar",
          "url": "plugin-4.0.170.jar",
          "size": 86156,
          "sha512": "acbc3661a8c55006a59e03f2c9cf3497592bebad5a4ac49a8dceef0aabed4812cc93d6974f98c9b861690b1147eac1c03af2c038cddf6eff65eb54ccf7a16bdc",
          "sha256": "c55fcb368e212e53e3c5acf31fb7995867d4dbc9cdfaaca9b70bdbe8fa7af317",
          "sha1": "b5e1dc9218ce773d569e712dd33e5b5650bcf746",
          "md5": "9cc961f22736f805e66882339714cc49"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
