{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.230",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.230.jar",
          "url": "plugin-4.0.230.jar",
          "size": 144826,
          "sha512": "9bf426b7a9c091ff7cc4173b2dd79a8864b3e2b19561600d3c07fe57a79b4e1b4d93f734ddf1e0b38a6086cda67ff72fee8df18963470baac51896baf5109fa5",
          "sha256": "9732641fd7a72f14cca08bb84f96300532e4f13157a488224304fc7fbd55c4b4",
          "sha1": "d9e35874fd4d0689eff6a5dded9c5550ad642dcc",
          "md5": "e8cdbc6f3f9dcbf974c12c044c52c5e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.230.jar",
          "url": "plugin-4.0.230.jar",
          "size": 144826,
          "sha512": "9bf426b7a9c091ff7cc4173b2dd79a8864b3e2b19561600d3c07fe57a79b4e1b4d93f734ddf1e0b38a6086cda67ff72fee8df18963470baac51896baf5109fa5",
          "sha256": "9732641fd7a72f14cca08bb84f96300532e4f13157a488224304fc7fbd55c4b4",
          "sha1": "d9e35874fd4d0689eff6a5dded9c5550ad642dcc",
          "md5": "e8cdbc6f3f9dcbf974c12c044c52c5e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
