{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.233",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.233.jar",
          "url": "plugin-4.0.233.jar",
          "size": 144826,
          "sha512": "1cea4752d69a67ed0df0ef9d4c51c028c737d1f70c8d810b42bc5d3687dbace60ec2833f5a7ddb3b02762a1fbb725f0a370afaf057c0372419edde04637def31",
          "sha256": "292780b7ebcba8486f79ab5a08ba49dba20cbdcc094ccd9f6aebfb5056bb3e82",
          "sha1": "205ef17fc351f3784c367ab38921cd7866a881e2",
          "md5": "e92b8fe050e31ee03eea8edb788ba84c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.233.jar",
          "url": "plugin-4.0.233.jar",
          "size": 144826,
          "sha512": "1cea4752d69a67ed0df0ef9d4c51c028c737d1f70c8d810b42bc5d3687dbace60ec2833f5a7ddb3b02762a1fbb725f0a370afaf057c0372419edde04637def31",
          "sha256": "292780b7ebcba8486f79ab5a08ba49dba20cbdcc094ccd9f6aebfb5056bb3e82",
          "sha1": "205ef17fc351f3784c367ab38921cd7866a881e2",
          "md5": "e92b8fe050e31ee03eea8edb788ba84c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
