{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.171",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.171.jar",
          "url": "plugin-4.0.171.jar",
          "size": 86765,
          "sha512": "2e5ecfae263d580fb4181bf0fe92fbb46f6d63744da19bd2fbbe2850c116ef0615099d344504cc3ca3ec4df0fda7d599263613448b066beb6da70293de270813",
          "sha256": "f3c303b30d3e59c6ff7f84a04b9355bd59534f840729123c55d30b5c748a8a0a",
          "sha1": "96ef0985d570bf0ece0fc8145fecbe8cec4d2d62",
          "md5": "14ac0484e83623710c86a67c0ef9a25c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.171.jar",
          "url": "plugin-4.0.171.jar",
          "size": 86765,
          "sha512": "2e5ecfae263d580fb4181bf0fe92fbb46f6d63744da19bd2fbbe2850c116ef0615099d344504cc3ca3ec4df0fda7d599263613448b066beb6da70293de270813",
          "sha256": "f3c303b30d3e59c6ff7f84a04b9355bd59534f840729123c55d30b5c748a8a0a",
          "sha1": "96ef0985d570bf0ece0fc8145fecbe8cec4d2d62",
          "md5": "14ac0484e83623710c86a67c0ef9a25c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
