{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.231",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.231.jar",
          "url": "plugin-4.0.231.jar",
          "size": 144826,
          "sha512": "8807e717b30bea397f35af2258f553c0c3fa383279c20415865bb054d54515b2b40edae06504df3dc28560ec03197c60ab5f7e574eed76c13777886bab6f1a9c",
          "sha256": "cc6893c532d9e25582f65f82a794a3c6e6f9f6496d5064e341aa735b8370fe62",
          "sha1": "105dffd7cee988116ab0769fa6cc31105e3a67ce",
          "md5": "d1970f87d1d0b16b7ff6d898abf33ae4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.231.jar",
          "url": "plugin-4.0.231.jar",
          "size": 144826,
          "sha512": "8807e717b30bea397f35af2258f553c0c3fa383279c20415865bb054d54515b2b40edae06504df3dc28560ec03197c60ab5f7e574eed76c13777886bab6f1a9c",
          "sha256": "cc6893c532d9e25582f65f82a794a3c6e6f9f6496d5064e341aa735b8370fe62",
          "sha1": "105dffd7cee988116ab0769fa6cc31105e3a67ce",
          "md5": "d1970f87d1d0b16b7ff6d898abf33ae4"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
