{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.210",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.210.aar",
          "url": "Applanga-4.0.210.aar",
          "size": 352635,
          "sha512": "7a471fa02032129fffc92942ff7259810306734dd3e02420ba4192475e396171ef6e0f465cc90ff9e3aa93a3cfe51ff223254a390c1cab3376181662be05afc3",
          "sha256": "3a1c006bcd13e2c9ddf9bbaac65b06bfc41fd16edab605823d142bf0b3f08a21",
          "sha1": "801d1a09c0b7cc64a1ffe39867489f846f4c4133",
          "md5": "0fc713ecc90a7ed04bf3e1024b5ea6ce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.210.aar",
          "url": "Applanga-4.0.210.aar",
          "size": 352635,
          "sha512": "7a471fa02032129fffc92942ff7259810306734dd3e02420ba4192475e396171ef6e0f465cc90ff9e3aa93a3cfe51ff223254a390c1cab3376181662be05afc3",
          "sha256": "3a1c006bcd13e2c9ddf9bbaac65b06bfc41fd16edab605823d142bf0b3f08a21",
          "sha1": "801d1a09c0b7cc64a1ffe39867489f846f4c4133",
          "md5": "0fc713ecc90a7ed04bf3e1024b5ea6ce"
        }
      ]
    }
  ]
}
