{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.173",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.173.jar",
          "url": "plugin-4.0.173.jar",
          "size": 92469,
          "sha512": "1c1834e1d782541d2f0c2cbc9314ee748458b7fedc9344076929a8a4cb9aed084ba043b108b653c4e5861e8262d1affe6a426935b39ee752de107ac9e5b3cf43",
          "sha256": "88aba0b1b7e84f06e908f7196e7d7a7f6c79aa99306b51c5ffd07e7b48ff54f2",
          "sha1": "a93a68391d68cec994a43279910778d0dbb740c5",
          "md5": "ec1c163b4920d9de2211ef24a51aba05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.173.jar",
          "url": "plugin-4.0.173.jar",
          "size": 92469,
          "sha512": "1c1834e1d782541d2f0c2cbc9314ee748458b7fedc9344076929a8a4cb9aed084ba043b108b653c4e5861e8262d1affe6a426935b39ee752de107ac9e5b3cf43",
          "sha256": "88aba0b1b7e84f06e908f7196e7d7a7f6c79aa99306b51c5ffd07e7b48ff54f2",
          "sha1": "a93a68391d68cec994a43279910778d0dbb740c5",
          "md5": "ec1c163b4920d9de2211ef24a51aba05"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
