{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.191",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.191.jar",
          "url": "plugin-4.0.191.jar",
          "size": 120933,
          "sha512": "06361ee920c70620b98a3adcdfd361280230c92f5e8e63edca51684f2eb7a5fff71c0062a824d43dcb4f96c508e1008a4ffda8dffcd964d9b8e1a54d9d320f76",
          "sha256": "2ab22f77cdf28ec48e02272a0107922f2a7bd09a80bc0b3dcfdca72300c6e1f2",
          "sha1": "879fe2c6aa668210391b5603845fbcace40b0d8e",
          "md5": "783ec234a1a8acfd45ad89ce749f3055"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.191.jar",
          "url": "plugin-4.0.191.jar",
          "size": 120933,
          "sha512": "06361ee920c70620b98a3adcdfd361280230c92f5e8e63edca51684f2eb7a5fff71c0062a824d43dcb4f96c508e1008a4ffda8dffcd964d9b8e1a54d9d320f76",
          "sha256": "2ab22f77cdf28ec48e02272a0107922f2a7bd09a80bc0b3dcfdca72300c6e1f2",
          "sha1": "879fe2c6aa668210391b5603845fbcace40b0d8e",
          "md5": "783ec234a1a8acfd45ad89ce749f3055"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
