{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.134",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "nd4mt2rqx5d4lcpq3smqrfk5x4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.134.jar",
          "url": "plugin-3.0.134.jar",
          "size": 122643,
          "sha512": "9acf6b7e43a4a04dc0c35eeba8e6b4b8aff75f53170d9ed33926044f9f49b908422a38ed25e4c9fc5084e63e5ace29bf30eed5d4b6850177f9c0fba3bdbf7bb4",
          "sha256": "807d7dfc420f66a50cefac07c25daaa62dcda29be8d6ecb8c440c69c30070cbd",
          "sha1": "321ac48f38411ad81e6390628d40f6fde7266ff8",
          "md5": "3ebdf5bd7f7f3ff486d9086df4a4e498"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.134.jar",
          "url": "plugin-3.0.134.jar",
          "size": 122643,
          "sha512": "9acf6b7e43a4a04dc0c35eeba8e6b4b8aff75f53170d9ed33926044f9f49b908422a38ed25e4c9fc5084e63e5ace29bf30eed5d4b6850177f9c0fba3bdbf7bb4",
          "sha256": "807d7dfc420f66a50cefac07c25daaa62dcda29be8d6ecb8c440c69c30070cbd",
          "sha1": "321ac48f38411ad81e6390628d40f6fde7266ff8",
          "md5": "3ebdf5bd7f7f3ff486d9086df4a4e498"
        }
      ]
    }
  ]
}
