{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.229",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.229.aar",
          "url": "Applanga-4.0.229.aar",
          "size": 407941,
          "sha512": "e86ed94429e00a896ac7011ef5d2d6f0d76bed32176d909880ddd91c1621259bb1877567b35a905ceb71b87e977b6a1e1f9ccd4a6fe2bf637d2e6170940b0f2f",
          "sha256": "a42ce80180c156a0f81bb52174df58c93a6888513ffa7a474274f47e42475e51",
          "sha1": "e28b17545a2a868b9dbc08a6bdc1432a5dfffcf3",
          "md5": "f7ab02e4832726240e935946e92f90cf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.229.aar",
          "url": "Applanga-4.0.229.aar",
          "size": 407941,
          "sha512": "e86ed94429e00a896ac7011ef5d2d6f0d76bed32176d909880ddd91c1621259bb1877567b35a905ceb71b87e977b6a1e1f9ccd4a6fe2bf637d2e6170940b0f2f",
          "sha256": "a42ce80180c156a0f81bb52174df58c93a6888513ffa7a474274f47e42475e51",
          "sha1": "e28b17545a2a868b9dbc08a6bdc1432a5dfffcf3",
          "md5": "f7ab02e4832726240e935946e92f90cf"
        }
      ]
    }
  ]
}
