{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.217",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.217.jar",
          "url": "plugin-4.0.217.jar",
          "size": 129878,
          "sha512": "2eceacf5e43186124f4102ce2dca56670ebed5a45eed01678a93dda21440021fc3e56cd03aaea37ef61a03e99916fb1b1c5ebf028aafdb082d6b013288aa77dc",
          "sha256": "c9a2a37f15c52aaebd3347996479db144317609c3de6c71403d40eec99235916",
          "sha1": "24e89ed26eb1a452dcb3f5c07ed0884f8ebb217d",
          "md5": "5760a7d4d3f81bff8a6d35bf17f4e158"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.217.jar",
          "url": "plugin-4.0.217.jar",
          "size": 129878,
          "sha512": "2eceacf5e43186124f4102ce2dca56670ebed5a45eed01678a93dda21440021fc3e56cd03aaea37ef61a03e99916fb1b1c5ebf028aafdb082d6b013288aa77dc",
          "sha256": "c9a2a37f15c52aaebd3347996479db144317609c3de6c71403d40eec99235916",
          "sha1": "24e89ed26eb1a452dcb3f5c07ed0884f8ebb217d",
          "md5": "5760a7d4d3f81bff8a6d35bf17f4e158"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
