{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.221",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.221.jar",
          "url": "plugin-4.0.221.jar",
          "size": 140761,
          "sha512": "e3805b24a1f2ab2445534a254bf3846d94e5d75547a30c92096a106862528a6a977fefc33e748733f066cba9c4995516651e310a83ed9359610c53ceecb95032",
          "sha256": "04089a441f584872ae4bb19355c85e61d98270a17ef94c3b2a751a6873699ddf",
          "sha1": "725ef3d614a18de53c52762bec4f7104577013c4",
          "md5": "4a3991de3d8a8880a93d72da9057226a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.221.jar",
          "url": "plugin-4.0.221.jar",
          "size": 140761,
          "sha512": "e3805b24a1f2ab2445534a254bf3846d94e5d75547a30c92096a106862528a6a977fefc33e748733f066cba9c4995516651e310a83ed9359610c53ceecb95032",
          "sha256": "04089a441f584872ae4bb19355c85e61d98270a17ef94c3b2a751a6873699ddf",
          "sha1": "725ef3d614a18de53c52762bec4f7104577013c4",
          "md5": "4a3991de3d8a8880a93d72da9057226a"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
