{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.180",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.180.jar",
          "url": "plugin-4.0.180.jar",
          "size": 97886,
          "sha512": "8d717a665fa741ea167f10c5b5c1f92cbdd4af9f95a6853d0f547340b8bb13ea1b6c0ff5344ba3b3b559f908e18d4a8965f0f64a47ff7b74dfc82f1d3c410255",
          "sha256": "91252fecf271975ae6d3bd3c67f1ff70e22044655e7a1805c4fcf895164432a2",
          "sha1": "ea46ce0df279ffc15a51c5d9e3b873573f9003cf",
          "md5": "0b6f1b846533b0fc62fc899dcf590c45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.180.jar",
          "url": "plugin-4.0.180.jar",
          "size": 97886,
          "sha512": "8d717a665fa741ea167f10c5b5c1f92cbdd4af9f95a6853d0f547340b8bb13ea1b6c0ff5344ba3b3b559f908e18d4a8965f0f64a47ff7b74dfc82f1d3c410255",
          "sha256": "91252fecf271975ae6d3bd3c67f1ff70e22044655e7a1805c4fcf895164432a2",
          "sha1": "ea46ce0df279ffc15a51c5d9e3b873573f9003cf",
          "md5": "0b6f1b846533b0fc62fc899dcf590c45"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
