{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.165",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "35xobzzldrheddwrlktafbzena"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.165.jar",
          "url": "plugin-3.0.165.jar",
          "size": 160144,
          "sha512": "9dca212c806fbe75028811b246e5107a9bd2e1398864802b4e73c74a73b3d434c2b3af177cb23ee217163b4ff81c9abd23f9c743436ebc9d2ea959f6e81da9c5",
          "sha256": "8e7c8d864e79afc789b76efea157a899a895408c836ba80c281ed09fc1fb54df",
          "sha1": "e483355db79fa4d2c59a20315d8835c8f577f39e",
          "md5": "d5a13992ed4dcec3bd0a7e2205ec2037"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.165.jar",
          "url": "plugin-3.0.165.jar",
          "size": 160144,
          "sha512": "9dca212c806fbe75028811b246e5107a9bd2e1398864802b4e73c74a73b3d434c2b3af177cb23ee217163b4ff81c9abd23f9c743436ebc9d2ea959f6e81da9c5",
          "sha256": "8e7c8d864e79afc789b76efea157a899a895408c836ba80c281ed09fc1fb54df",
          "sha1": "e483355db79fa4d2c59a20315d8835c8f577f39e",
          "md5": "d5a13992ed4dcec3bd0a7e2205ec2037"
        }
      ]
    }
  ]
}
