{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.225",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.225.jar",
          "url": "plugin-4.0.225.jar",
          "size": 144473,
          "sha512": "15d9dcd112c9b9f667bbcc31a875ac0efc170131595d7376f32ad5d7e9b7afb43d3a7189e2adafec0f1652a1d40b62c699b60fcd42d095b5bb7d7e7442443136",
          "sha256": "c78b49dd6e409ed280fd219bcc8772c0bcf925e6f17c2a69df4b44cace8557d3",
          "sha1": "e6c58769120169156a9fa12cc9f1563ba1b61d49",
          "md5": "a513b8b8fda39dec45db460a038bc298"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.225.jar",
          "url": "plugin-4.0.225.jar",
          "size": 144473,
          "sha512": "15d9dcd112c9b9f667bbcc31a875ac0efc170131595d7376f32ad5d7e9b7afb43d3a7189e2adafec0f1652a1d40b62c699b60fcd42d095b5bb7d7e7442443136",
          "sha256": "c78b49dd6e409ed280fd219bcc8772c0bcf925e6f17c2a69df4b44cace8557d3",
          "sha1": "e6c58769120169156a9fa12cc9f1563ba1b61d49",
          "md5": "a513b8b8fda39dec45db460a038bc298"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
