{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.167",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "2b2ua6ludjd4bcqmlrzihodham"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.167.jar",
          "url": "plugin-3.0.167.jar",
          "size": 161515,
          "sha512": "76816eb2e73ab0592ed9751080111e886479971e4e175165377c2cabd6ba8841085b29f071676d02b3cf998041f5dcb4577b1fcc1a2b5ee0fb469be53d033550",
          "sha256": "cbdaf1c416a7187a63522109e6ba7ac457d5d17a500a4a02cc91d505fc52761d",
          "sha1": "65de3358789c0544630e91972c2d9e02f8f39a80",
          "md5": "57c9c12bfd11201154a4b4957ff30aa5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.167.jar",
          "url": "plugin-3.0.167.jar",
          "size": 161515,
          "sha512": "76816eb2e73ab0592ed9751080111e886479971e4e175165377c2cabd6ba8841085b29f071676d02b3cf998041f5dcb4577b1fcc1a2b5ee0fb469be53d033550",
          "sha256": "cbdaf1c416a7187a63522109e6ba7ac457d5d17a500a4a02cc91d505fc52761d",
          "sha1": "65de3358789c0544630e91972c2d9e02f8f39a80",
          "md5": "57c9c12bfd11201154a4b4957ff30aa5"
        }
      ]
    }
  ]
}
