{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.188",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.188.jar",
          "url": "plugin-4.0.188.jar",
          "size": 120430,
          "sha512": "f459383808c2849d025d3844a29c8ade51920ffe3139e72dac0cad5b45ec1dcc520632e072469c2f6a3a9f7abc64dd50aa10597dcbde1adeffdfc62a429be31b",
          "sha256": "74a089fc1b5a9537106a67bc2d0b4c11923f6de99951f08a856b8589d81b635b",
          "sha1": "947d5447a22368a6ad5eb6440e07fdd993870525",
          "md5": "8ab044bfe2c90bff1a9d66518bf72965"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.188.jar",
          "url": "plugin-4.0.188.jar",
          "size": 120430,
          "sha512": "f459383808c2849d025d3844a29c8ade51920ffe3139e72dac0cad5b45ec1dcc520632e072469c2f6a3a9f7abc64dd50aa10597dcbde1adeffdfc62a429be31b",
          "sha256": "74a089fc1b5a9537106a67bc2d0b4c11923f6de99951f08a856b8589d81b635b",
          "sha1": "947d5447a22368a6ad5eb6440e07fdd993870525",
          "md5": "8ab044bfe2c90bff1a9d66518bf72965"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
