{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.174",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.174.jar",
          "url": "plugin-4.0.174.jar",
          "size": 93834,
          "sha512": "98b65ea6f5e972d49e850030b2b8937a4ee29d762f479fd9b8efb4ef060cd63bd94c66f8c9b2538f80e658cf9ad768ff53987f912a267e76c411890bec57bddd",
          "sha256": "ead7d539e143550df4e6b4b3f57222f5a52983cbbaabc57431db44de7190cd2e",
          "sha1": "d37532a51f903c2bf6166f120741c931a075186f",
          "md5": "459d8ebf9e079aad7c596ff796d24377"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.174.jar",
          "url": "plugin-4.0.174.jar",
          "size": 93834,
          "sha512": "98b65ea6f5e972d49e850030b2b8937a4ee29d762f479fd9b8efb4ef060cd63bd94c66f8c9b2538f80e658cf9ad768ff53987f912a267e76c411890bec57bddd",
          "sha256": "ead7d539e143550df4e6b4b3f57222f5a52983cbbaabc57431db44de7190cd2e",
          "sha1": "d37532a51f903c2bf6166f120741c931a075186f",
          "md5": "459d8ebf9e079aad7c596ff796d24377"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
