{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.142",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "n6jrvpplovggphdtn5vb7ksnia"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.142.jar",
          "url": "plugin-3.0.142.jar",
          "size": 123258,
          "sha512": "619d7dbef144359ba5963634b53d721966a0122f383bbed26dd56e7baa111c558c37e17180dc51f6d7bfde7f2e52c162d229de321e101a7d2e144a682a27cbe7",
          "sha256": "aaa40940a7628636f96161584a38f962a5eab0462a55913203a1120aa8b1c1b7",
          "sha1": "799b664bc2670a82ae8e74da31fe0427b0d63743",
          "md5": "266137860b5b7f3b9b237bbd7260b623"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.27.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.142.jar",
          "url": "plugin-3.0.142.jar",
          "size": 123258,
          "sha512": "619d7dbef144359ba5963634b53d721966a0122f383bbed26dd56e7baa111c558c37e17180dc51f6d7bfde7f2e52c162d229de321e101a7d2e144a682a27cbe7",
          "sha256": "aaa40940a7628636f96161584a38f962a5eab0462a55913203a1120aa8b1c1b7",
          "sha1": "799b664bc2670a82ae8e74da31fe0427b0d63743",
          "md5": "266137860b5b7f3b9b237bbd7260b623"
        }
      ]
    }
  ]
}
