{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.160",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "crvb7axlcvdwddob4lduhjabny"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.160.jar",
          "url": "plugin-3.0.160.jar",
          "size": 151665,
          "sha512": "9ed776eae3ed0ffb990fa1d313a898bf9dfa359ae444358ed6bf4b9b0896b8dbb86916784a28adcba9b9cdaa7473f6457c15902cdaa8f764497982b8d98930ed",
          "sha256": "72963d8e1af03b23ac4bc83f108b5f0774ca620f13e4441e48c8673562876dca",
          "sha1": "450b66f0c122a99738d429780021c1d1a6daffb9",
          "md5": "f4e6fa291346c7fd74714bd19418ab23"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.160.jar",
          "url": "plugin-3.0.160.jar",
          "size": 151665,
          "sha512": "9ed776eae3ed0ffb990fa1d313a898bf9dfa359ae444358ed6bf4b9b0896b8dbb86916784a28adcba9b9cdaa7473f6457c15902cdaa8f764497982b8d98930ed",
          "sha256": "72963d8e1af03b23ac4bc83f108b5f0774ca620f13e4441e48c8673562876dca",
          "sha1": "450b66f0c122a99738d429780021c1d1a6daffb9",
          "md5": "f4e6fa291346c7fd74714bd19418ab23"
        }
      ]
    }
  ]
}
