{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.218",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.218.jar",
          "url": "plugin-4.0.218.jar",
          "size": 129878,
          "sha512": "41656c7776c72409d83c697d28974f44336de0eaea9e08b1194a25b53ae36519e994850e175c9ca01f31ce974c031f953c2c3ae7d225206538f1e539f7c29b25",
          "sha256": "5bd72e999102d71bf4ebea8c5a2dd815da36fb18d4dffc7f5e7e6649a91c1546",
          "sha1": "4acc96e85ab5e085ff1bda11943df21aa4ca6264",
          "md5": "63e3b72cd8b3f3898c8671b117252c32"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.218.jar",
          "url": "plugin-4.0.218.jar",
          "size": 129878,
          "sha512": "41656c7776c72409d83c697d28974f44336de0eaea9e08b1194a25b53ae36519e994850e175c9ca01f31ce974c031f953c2c3ae7d225206538f1e539f7c29b25",
          "sha256": "5bd72e999102d71bf4ebea8c5a2dd815da36fb18d4dffc7f5e7e6649a91c1546",
          "sha1": "4acc96e85ab5e085ff1bda11943df21aa4ca6264",
          "md5": "63e3b72cd8b3f3898c8671b117252c32"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
