{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.159",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "yzuwlfjtxfbenbdbubkj2rgf4e"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.159.jar",
          "url": "plugin-3.0.159.jar",
          "size": 151664,
          "sha512": "63222e8c3e36a7d3d49e3c043b0387224ea204e17e11c11f324a9987430de7f53e22f1195b0c7cdba48f1380e4384de2ba7fb15f22de7096f1d135fa5ebdb6fb",
          "sha256": "31fb7c0f22f8777c5822b8e0c148a950581b78fe04c49b44ab1921778f163dc2",
          "sha1": "edd45b1879f22ea55a51afdad473de4afad55405",
          "md5": "46616eedfbaf424f065488fec3ff00bf"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.159.jar",
          "url": "plugin-3.0.159.jar",
          "size": 151664,
          "sha512": "63222e8c3e36a7d3d49e3c043b0387224ea204e17e11c11f324a9987430de7f53e22f1195b0c7cdba48f1380e4384de2ba7fb15f22de7096f1d135fa5ebdb6fb",
          "sha256": "31fb7c0f22f8777c5822b8e0c148a950581b78fe04c49b44ab1921778f163dc2",
          "sha1": "edd45b1879f22ea55a51afdad473de4afad55405",
          "md5": "46616eedfbaf424f065488fec3ff00bf"
        }
      ]
    }
  ]
}
