{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.190",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.190.jar",
          "url": "plugin-4.0.190.jar",
          "size": 120933,
          "sha512": "d85570bcee28d89eb8a8dbc6f1372abd37a24a6fea26d1b4b2fce86c6e60deeecfe6238744c1461f6bb6e4c5c6dc14cc5486b2e49caed17923223d665dffa1da",
          "sha256": "fc3e87ad4dbc10b06c07a010f87ebf81c58132bd66c3d1333b61dfc9dad6905b",
          "sha1": "123891bf57689577d24369fbb4635a1dc560ab8f",
          "md5": "1a45813d026765f7b8c096e4f41373bb"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.190.jar",
          "url": "plugin-4.0.190.jar",
          "size": 120933,
          "sha512": "d85570bcee28d89eb8a8dbc6f1372abd37a24a6fea26d1b4b2fce86c6e60deeecfe6238744c1461f6bb6e4c5c6dc14cc5486b2e49caed17923223d665dffa1da",
          "sha256": "fc3e87ad4dbc10b06c07a010f87ebf81c58132bd66c3d1333b61dfc9dad6905b",
          "sha1": "123891bf57689577d24369fbb4635a1dc560ab8f",
          "md5": "1a45813d026765f7b8c096e4f41373bb"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
