{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.227",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.227.jar",
          "url": "plugin-4.0.227.jar",
          "size": 144523,
          "sha512": "2fa247b752c883ec82aec7d2376de9d42943a1cb5ff5a9278dca8d9a039f64e10312bb16cf6a80cad56c2b25df7e7f1ae491315646aaa95ce498f1f37fed1540",
          "sha256": "d09b57001c505eb31f203494aaaa54398a3b21051961e35d5f56550170c4e7a7",
          "sha1": "e0bc059f0daeff167d8307ecd3649fcbcfb8d44b",
          "md5": "782b00167f389a612d8e01caa0bd81e2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.227.jar",
          "url": "plugin-4.0.227.jar",
          "size": 144523,
          "sha512": "2fa247b752c883ec82aec7d2376de9d42943a1cb5ff5a9278dca8d9a039f64e10312bb16cf6a80cad56c2b25df7e7f1ae491315646aaa95ce498f1f37fed1540",
          "sha256": "d09b57001c505eb31f203494aaaa54398a3b21051961e35d5f56550170c4e7a7",
          "sha1": "e0bc059f0daeff167d8307ecd3649fcbcfb8d44b",
          "md5": "782b00167f389a612d8e01caa0bd81e2"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
