{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "plugin",
    "version": "3.0.153",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "iyjnnnijgfcqldcpa2z3d2leca"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "plugin-3.0.153.jar",
          "url": "plugin-3.0.153.jar",
          "size": 151665,
          "sha512": "533194199bae2bc3579adaa20c5eb5dbb28c175f7869a83424004b40d2ca0bd9eefea18ced8ada4153f9378b4dbb0e80f6629b0ac243c0338f9438732f355f23",
          "sha256": "34efa90b21a6007e3f93a24fb514885550c6903432afa3a8993bb980699b174d",
          "sha1": "b24d3200ad5845e7ce853f1dfd368b962949aa34",
          "md5": "f3b3cde77e6cf480509eb62bf80b47d0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "org.javassist",
          "module": "javassist",
          "version": {
            "requires": "3.28.0-GA"
          }
        },
        {
          "group": "com.github.stephanenicolas.javassist",
          "module": "javassist-build-plugin-api",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android",
          "module": "android",
          "version": {
            "requires": "4.1.1.4"
          }
        },
        {
          "group": "com.google.android",
          "module": "support-v4",
          "version": {
            "requires": "r7"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.17.3"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-3.0.153.jar",
          "url": "plugin-3.0.153.jar",
          "size": 151665,
          "sha512": "533194199bae2bc3579adaa20c5eb5dbb28c175f7869a83424004b40d2ca0bd9eefea18ced8ada4153f9378b4dbb0e80f6629b0ac243c0338f9438732f355f23",
          "sha256": "34efa90b21a6007e3f93a24fb514885550c6903432afa3a8993bb980699b174d",
          "sha1": "b24d3200ad5845e7ce853f1dfd368b962949aa34",
          "md5": "f3b3cde77e6cf480509eb62bf80b47d0"
        }
      ]
    }
  ]
}
