{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.214",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.214.jar",
          "url": "plugin-4.0.214.jar",
          "size": 124203,
          "sha512": "e3676c9a84bb07ff7120bbced2845963a01098fe7187f10490742380725425f3f481ba1e76fdfb8649b43a9f0551a8e4d89c61f2b41d4b92a0e16365b894f827",
          "sha256": "fa12c03aaf657aea3559f5ece02ab5cd441c1d026fc30a6316c54febbb248d0e",
          "sha1": "7cc0c4284ba25c32d5cfce78628e71d6963677b6",
          "md5": "7ccd426bc953af27aad280d09d4f30a6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.214.jar",
          "url": "plugin-4.0.214.jar",
          "size": 124203,
          "sha512": "e3676c9a84bb07ff7120bbced2845963a01098fe7187f10490742380725425f3f481ba1e76fdfb8649b43a9f0551a8e4d89c61f2b41d4b92a0e16365b894f827",
          "sha256": "fa12c03aaf657aea3559f5ece02ab5cd441c1d026fc30a6316c54febbb248d0e",
          "sha1": "7cc0c4284ba25c32d5cfce78628e71d6963677b6",
          "md5": "7ccd426bc953af27aad280d09d4f30a6"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
