{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.android",
    "module": "Applanga",
    "version": "4.0.172",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "vanillaReleaseVariantVanillaReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.172.aar",
          "url": "Applanga-4.0.172.aar",
          "size": 227989,
          "sha512": "9174072ce03e5bb4861f3ee2e0a769e72bfc2cf03160e0f2d95734a509bfbdcf94c91578e3131f987aa22dd59cecd04ba236ede51aaa5e44c81355312b2dd0af",
          "sha256": "63552ff3d38100551c37dff2e5cf7ffa1f3e077b5dcaa5f7f4f716e48bed8139",
          "sha1": "b948ab044b2fd9e131b11c4c597f15b985a9ed91",
          "md5": "e13d8b34965015972e9127000d3b366d"
        }
      ]
    },
    {
      "name": "vanillaReleaseVariantVanillaReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "io.github.inflationx",
          "module": "viewpump",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "Applanga-4.0.172.aar",
          "url": "Applanga-4.0.172.aar",
          "size": 227989,
          "sha512": "9174072ce03e5bb4861f3ee2e0a769e72bfc2cf03160e0f2d95734a509bfbdcf94c91578e3131f987aa22dd59cecd04ba236ede51aaa5e44c81355312b2dd0af",
          "sha256": "63552ff3d38100551c37dff2e5cf7ffa1f3e077b5dcaa5f7f4f716e48bed8139",
          "sha1": "b948ab044b2fd9e131b11c4c597f15b985a9ed91",
          "md5": "e13d8b34965015972e9127000d3b366d"
        }
      ]
    }
  ]
}
