{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.184",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.184.jar",
          "url": "plugin-4.0.184.jar",
          "size": 117132,
          "sha512": "5f66bdc41f414bdbadb5cfb52c7957a8ce6486a5cdbdc0ed54aade75f0f79623a7c11da0ffae7506fa750601bc2696dfdce7b878bc73707035702d6ebd6e5765",
          "sha256": "3a53c4ef17d1ab8bc75733e1f344a404027d392cd78167269469bcf707412f88",
          "sha1": "397a493070a393312f5c1672c96d356cf023afda",
          "md5": "11897b65e9bbb9daa9b5e1b59a927bf7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.184.jar",
          "url": "plugin-4.0.184.jar",
          "size": 117132,
          "sha512": "5f66bdc41f414bdbadb5cfb52c7957a8ce6486a5cdbdc0ed54aade75f0f79623a7c11da0ffae7506fa750601bc2696dfdce7b878bc73707035702d6ebd6e5765",
          "sha256": "3a53c4ef17d1ab8bc75733e1f344a404027d392cd78167269469bcf707412f88",
          "sha1": "397a493070a393312f5c1672c96d356cf023afda",
          "md5": "11897b65e9bbb9daa9b5e1b59a927bf7"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
