{
  "formatVersion": "1.1",
  "component": {
    "group": "com.applanga.gradle",
    "module": "plugin",
    "version": "4.0.202",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "plugin-4.0.202.jar",
          "url": "plugin-4.0.202.jar",
          "size": 124189,
          "sha512": "76e7ed3e4b00345371bab519cb715d92da03dd9f65a65c21042b9bf5a80faf72921a8e0b050f6b70c2072bf7c26720ea484873ee52c70b761d8a8f0dcb1f0182",
          "sha256": "4ecf792620bc768e84d2e4d134cffa81c412f196baf24fb52088096e7349eff3",
          "sha1": "58f02d2318232f206821d70f386ab8f3b1d863b1",
          "md5": "fbc6193ff43878424252281e0389a18e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.applanga.android",
          "module": "annotation",
          "version": {
            "requires": "1.0.1"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.31"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle-api",
          "version": {
            "requires": "7.2.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-util",
          "version": {
            "requires": "7.0"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-4.0.202.jar",
          "url": "plugin-4.0.202.jar",
          "size": 124189,
          "sha512": "76e7ed3e4b00345371bab519cb715d92da03dd9f65a65c21042b9bf5a80faf72921a8e0b050f6b70c2072bf7c26720ea484873ee52c70b761d8a8f0dcb1f0182",
          "sha256": "4ecf792620bc768e84d2e4d134cffa81c412f196baf24fb52088096e7349eff3",
          "sha1": "58f02d2318232f206821d70f386ab8f3b1d863b1",
          "md5": "fbc6193ff43878424252281e0389a18e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      }
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      }
    }
  ]
}
